DROP TABLE IF EXISTS Osallistuminen CASCADE;
DROP TABLE IF EXISTS Tapahtuman_aihe CASCADE;
DROP TABLE IF EXISTS Kayttajan_kiinnostus CASCADE;
DROP TABLE IF EXISTS Tapahtuma CASCADE; 
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Kiinnostustagi CASCADE;

